//@version=5
indicator(title='CRUDE V3', shorttitle='CRUDE V3', precision=2, overlay=true)

smaValue = input.int(70, title='SMA Length', step=1)
distSMA = input.float(0.022, title='distSMA', step=0.001)

sma = ta.sma(close, smaValue)

gaps = sma * (1 + distSMA)
gapb = sma / (1 + distSMA)
gapsHalf = sma * (1 + distSMA / 2)
gapbHalf = sma / (1 + distSMA / 2)

var bool inBuyPosition = false
var bool inSellPosition = false
var bool halvedBuy = false
var bool halvedSell = false

BUY = ta.crossover(close[1], sma) and close[1] > open[1] and high[0] > high[1] and close[0] > open[0]
SELL = ta.crossunder(low[1], sma) and close[1] < open[1] and low[0] < low[1] and close[0] < open[0]
CBTP = inBuyPosition and (high > gaps)
CBSL = inBuyPosition and (low < gapbHalf)
CBTP_HALF = inBuyPosition and not halvedBuy and (high > gapsHalf)
CSTP = inSellPosition and (low < gapb)
CSSL = inSellPosition and (high > gapsHalf)
CSTP_HALF = inSellPosition and not halvedSell and (low < gapbHalf)

if (BUY)
    inBuyPosition := true
    inSellPosition := false
    halvedBuy := false
    halvedSell := false
else if (SELL)
    inBuyPosition := false
    inSellPosition := true
    halvedBuy := false
    halvedSell := false
else if (CBTP or CBSL or CSTP or CSSL)
    inBuyPosition := false
    inSellPosition := false
    halvedBuy := false
    halvedSell := false
else if (CBTP_HALF)
    inBuyPosition := true
    inSellPosition := false
    halvedBuy := true
    halvedSell := false
else if (CSTP_HALF)
    inBuyPosition := false
    inSellPosition := true
    halvedBuy := false
    halvedSell := true

plotshape(SELL, title='SELL', style=shape.labeldown, color=color.new(color.red, 30), text='S', textcolor=color.new(color.black, 30))
plotshape(BUY, title='BUY', style=shape.labelup, color=color.new(color.aqua, 30), text='B', textcolor=color.new(color.black, 30), location=location.belowbar)
plotshape(CBTP_HALF, title='CBTP_HALF', style=shape.labeldown, color=color.new(color.yellow, 40), text='CBTP_HALF', textcolor=color.black)
plotshape(CSTP_HALF, title='CSTP_HALF', style=shape.labelup, color=color.new(color.yellow, 40), text='CSTP_HALF', textcolor=color.black, location=location.belowbar)
plotshape(CBTP, title='CBTP', style=shape.labeldown, color=color.new(color.orange, 0), text='CBTP', textcolor=color.black)
plotshape(CSTP, title='CSTP', style=shape.labelup, color=color.new(color.orange, 0), text='CBTP', textcolor=color.black, location=location.belowbar)
plotshape(CBSL, title='CBSL', style=shape.labelup, color=#f1c7c7, text='CBSL', textcolor=color.black, location=location.belowbar)
plotshape(CSSL, title='CSSL', style=shape.labeldown, color=#f1c7c7, text='CSSL', textcolor=color.black)

plot(sma, title='SMA', color=color.white, linewidth=1)
plot(gaps, title='gaps', color=color.new(color.green, 30), linewidth=1)
plot(gapb, title='gapb', color=color.new(color.red, 30), linewidth=1)
plot(gapsHalf, title='gapsHalf', color=color.new(color.green, 60), linewidth=1)
plot(gapbHalf, title='gapbHalf', color=color.new(color.red, 60), linewidth=1)
